jarsigner -keystore OpenCCVKeyStore -storepass $1 ./OpenCCV.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/gluegen-rt/gluegen-rt.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/gluegen-rt/gluegen-rt-natives-macosx-ppc.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/gluegen-rt/gluegen-rt-natives-solaris-i586.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/gluegen-rt/gluegen-rt-natives-windows-amd64.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/gluegen-rt/gluegen-rt-natives-linux-amd64.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/gluegen-rt/gluegen-rt-natives-macosx-universal.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/gluegen-rt/gluegen-rt-natives-solaris-sparc.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/gluegen-rt/gluegen-rt-natives-windows-i586.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/gluegen-rt/gluegen-rt-natives-linux-i586.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/gluegen-rt/gluegen-rt-natives-solaris-amd64.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/gluegen-rt/gluegen-rt-natives-solaris-sparcv9.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/jogl/jogl.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/jogl/jogl-natives-linux-i586.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/jogl/jogl-natives-macosx-universal.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/jogl/jogl-natives-solaris-i586.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/jogl/jogl-natives-solaris-sparcv9.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/jogl/jogl-natives-windows-i586.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/jogl/jogl-natives-linux-amd64.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/jogl/jogl-natives-macosx-ppc.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/jogl/jogl-natives-solaris-amd64.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/jogl/jogl-natives-solaris-sparc.jar $2
jarsigner -keystore OpenCCVKeyStore -storepass $1 ./resources/jogl/jogl-natives-windows-amd64.jar $2